    name: Deploy JavaDocs to GitHub Pages

    on:
      push:
        branches:
          - main  # main 브랜치에 푸시할 때마다 이 작업 실행

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: '17'

        - name: Grant execute permission for Gradle Wrapper
          run: chmod +x gradlew

        - name: Build with Gradle
          run: ./gradlew build

        - name: Generate JavaDocs using Dokka
          run: ./gradlew dokkaHtml

        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./build/dokka/html
            publish_branch: gh-pages
